// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf-demo-user/internal/logic/bizctx"
	_ "gf-demo-user/internal/logic/jwt"
	_ "gf-demo-user/internal/logic/middleware"
	_ "gf-demo-user/internal/logic/session"
	_ "gf-demo-user/internal/logic/user"
)
